FROM python:3.7-alpine as build
RUN adduser -s /bin/sh -D -u 1000 yema yema \
    && apk --no-cache update \
    && apk --no-cache add \
        postgresql-dev \
        zlib-dev \
        gcc \
        musl-dev \
        libffi-dev \
        rust \
        cargo
WORKDIR /code/
COPY ./api/requirements ./requirements
RUN pip install -r ./requirements/base.txt
COPY --chown=yema:yema . ./code


FROM build as dev
WORKDIR /code/
RUN pip install -r ./requirements/local.txt
USER yema